app_password="Axo2025!"
OPENAI_API_KEY= "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"
